// <auto-generated />
namespace TripAdvertisement.DAL.AppMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPreferences : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPreferences));
        
        string IMigrationMetadata.Id
        {
            get { return "201708241612527_AddPreferences"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
