// <auto-generated />
namespace TripAdvertisement.DAL.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class updateForeignKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateForeignKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201708150725127_updateForeignKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
